/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package infoprojekt;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author info
 */
public class Visuell extends javax.swing.JFrame {

    private Graph graph;
   

    /**
     * Creates new form Visuell
     */
    public Visuell() {
        initComponents();

        runBtn.setEnabled(false);
        runBtn.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nodePanel = new javax.swing.JPanel();
        resetBtn = new javax.swing.JButton();
        delaySlider = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        erstelleBaumBtn = new javax.swing.JButton();
        anzahlKnotenTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        platzierungModusCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        runBtn = new javax.swing.JButton();
        delayLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nodePanel.setBackground(new java.awt.Color(0, 0, 0));
        nodePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nodePanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout nodePanelLayout = new javax.swing.GroupLayout(nodePanel);
        nodePanel.setLayout(nodePanelLayout);
        nodePanelLayout.setHorizontalGroup(
            nodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        nodePanelLayout.setVerticalGroup(
            nodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );

        resetBtn.setText("Zürücksetzen");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        delaySlider.setMaximum(1000);
        delaySlider.setMinorTickSpacing(100);
        delaySlider.setPaintTicks(true);
        delaySlider.setSnapToTicks(true);
        delaySlider.setToolTipText("Sekunden");
        delaySlider.setNextFocusableComponent(delaySlider);

        jLabel1.setText("Simulation (Takt):");

        erstelleBaumBtn.setText("Erstellen");
        erstelleBaumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erstelleBaumBtnActionPerformed(evt);
            }
        });

        anzahlKnotenTxt.setText("5");
        anzahlKnotenTxt.setToolTipText("Anzahl Knoten");
        anzahlKnotenTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anzahlKnotenTxtActionPerformed(evt);
            }
        });

        jLabel3.setText("Anzahl Knoten:");

        platzierungModusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zufällig (Automatisch)", "Manuell (Maus)", " " }));
        platzierungModusCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platzierungModusComboActionPerformed(evt);
            }
        });

        jLabel4.setText("Platzierung:");

        runBtn.setText("Los!");
        runBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nodePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(40, 40, 40)
                                .addComponent(platzierungModusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(erstelleBaumBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)
                        .addComponent(anzahlKnotenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delayLbl))
                    .addComponent(delaySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nodePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(anzahlKnotenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(platzierungModusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(delayLbl))
                        .addGap(15, 15, 15)
                        .addComponent(delaySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(erstelleBaumBtn)
                    .addComponent(resetBtn)
                    .addComponent(runBtn))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void erstelleBaumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erstelleBaumBtnActionPerformed
        if (platzierungModusCombo.getSelectedIndex() == 0) {
            if (anzahlKnotenTxt.getText().isEmpty())
            {
                anzahlKnotenTxt.setText("2");
            }
            int nodeCount = Integer.valueOf(anzahlKnotenTxt.getText());
            if (nodeCount <= 0) {
                nodeCount = 2;
                anzahlKnotenTxt.setText(String.valueOf(nodeCount));
            }
            //Zufällige Anordnung
            platziereZufaellig(
                    Integer.valueOf(anzahlKnotenTxt.getText()),
                    nodePanel.getWidth(), nodePanel.getHeight()
            );
            drawGraph();
            runBtn.setEnabled(true);
        } else {
            //Manuell
        }
    }//GEN-LAST:event_erstelleBaumBtnActionPerformed

    private void runBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runBtnActionPerformed
        graph.setDelay(delaySlider.getValue());

        graph.minimalSanningTree(nodePanel.getGraphics());
        runBtn.setEnabled(false);

    }//GEN-LAST:event_runBtnActionPerformed

    private void platzierungModusComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platzierungModusComboActionPerformed
        reset();
        anzahlKnotenTxt.setText("");
        erstelleBaumBtn.setVisible(platzierungModusCombo.getSelectedIndex() == 0);

                
    }//GEN-LAST:event_platzierungModusComboActionPerformed

    private void anzahlKnotenTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anzahlKnotenTxtActionPerformed
        try {
            if (Integer.valueOf(anzahlKnotenTxt.getText()) < 1) {
                anzahlKnotenTxt.setText("0");
            }
        } catch (NumberFormatException e) {
            anzahlKnotenTxt.setText("0");
        }
    }//GEN-LAST:event_anzahlKnotenTxtActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        reset();

        runBtn.setEnabled(false);

    }//GEN-LAST:event_resetBtnActionPerformed

    private void nodePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nodePanelMouseClicked

        if (platzierungModusCombo.getSelectedIndex() == 1) {
            Graphics2D g2d = (Graphics2D) nodePanel.getGraphics();
            int x = evt.getX() - Graph.nodeWidth / 2;
            int y = evt.getY() - Graph.nodeWidth / 2;
            graph.addNode(graph.getNodeCount(), x, y);
            graph.draw(g2d);
            anzahlKnotenTxt.setText(String.valueOf(graph.getNodeCount()));
        }
       
            runBtn.setEnabled(graph.getNodeCount() > 1);

    }//GEN-LAST:event_nodePanelMouseClicked

    private void reset() {

        graph = new Graph(nodePanel.getWidth(), nodePanel.getHeight());
        graph.init(Integer.valueOf(anzahlKnotenTxt.getText()));
       
        nodePanel.getGraphics().fillRect(0, 0, nodePanel.getWidth(), nodePanel.getHeight());
      
      
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visuell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visuell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visuell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visuell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visuell().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anzahlKnotenTxt;
    private javax.swing.JLabel delayLbl;
    private javax.swing.JSlider delaySlider;
    private javax.swing.JButton erstelleBaumBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel nodePanel;
    private javax.swing.JComboBox<String> platzierungModusCombo;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton runBtn;
    // End of variables declaration//GEN-END:variables

    private void platziereZufaellig(int count, int screenWidth, int screenHeight) {

        if (count < 0) {
            return;
        }

        reset();

        graph = new Graph(screenWidth, screenHeight);
        graph.init(count);
        graph.fillRandomly();
        
    }

    private void drawGraph() {
        
        graph.draw(nodePanel.getGraphics());
        
    }

}
