/**
 * Project:
 *
 *  Minimal Spanning Trees
 *  ESG Kornwestheim, KS1
 *
 * Authors:
 *
 * -´Aykon Kücük
 * - Leon Broßwitz
 *
 * (c) June 2018
 */
package infoprojekt;

import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;

/**
 *
 * @author info
 */
public class Visuell extends javax.swing.JFrame implements FocusListener, ActionListener {

    private static final int MINIMUM_NODES = 2;
    private static final int MAXIMUM_NODES = 2500;

    private Graph graph;

    /**
     * Creates new form Visuell
     */
    public Visuell() {
        initComponents();

        runBtn.setEnabled(false);
        runBtn.setVisible(true);

        anzahlKnotenTxt.addFocusListener(this);
        anzahlKnotenTxt.addActionListener(this);
        
         
   
    }

    private void checkAndFixValue() {
        if (anzahlKnotenTxt.getText().isEmpty()) {
            anzahlKnotenTxt.setText(String.valueOf(MINIMUM_NODES));
            return;
        }
        try {
            int value = Integer.parseInt(anzahlKnotenTxt.getText());
            if (value < 2) {
                anzahlKnotenTxt.setText(String.valueOf(MINIMUM_NODES));
            } else if (value > MAXIMUM_NODES) {
                anzahlKnotenTxt.setText(String.valueOf(MAXIMUM_NODES));
            }
        } catch (NumberFormatException e) {
            anzahlKnotenTxt.setText(String.valueOf(MINIMUM_NODES));
            return;

        }
    }

    public void focusLost(FocusEvent e) {
        checkAndFixValue();
    }

    public void actionPerformed(ActionEvent event) {

        checkAndFixValue();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nodePanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        anzahlKnotenTxt = new javax.swing.JTextField();
        graphBuildCbx = new javax.swing.JCheckBox();
        platzierungModusCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        erstelleBaumBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        totalEdgesLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        runBtn = new javax.swing.JButton();
        delayLbl = new javax.swing.JLabel();
        delaySlider = new javax.swing.JSlider();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Minimalaufspannende Bäume");
        setMaximumSize(new java.awt.Dimension(1024, 1024));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(640, 640));

        nodePanel.setBackground(new java.awt.Color(0, 0, 0));
        nodePanel.setForeground(new java.awt.Color(255, 255, 255));
        nodePanel.setToolTipText("");
        nodePanel.setMaximumSize(new java.awt.Dimension(1024, 1024));
        nodePanel.setName(""); // NOI18N
        nodePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nodePanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout nodePanelLayout = new javax.swing.GroupLayout(nodePanel);
        nodePanel.setLayout(nodePanelLayout);
        nodePanelLayout.setHorizontalGroup(
            nodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        nodePanelLayout.setVerticalGroup(
            nodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Graph"));

        jLabel3.setText("Anzahl Knoten:");

        anzahlKnotenTxt.setText("10");
        anzahlKnotenTxt.setToolTipText("Anzahl Knoten");
        anzahlKnotenTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anzahlKnotenTxtActionPerformed(evt);
            }
        });

        graphBuildCbx.setText("Graphaufbau zeigen");

        platzierungModusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zufällig (Automatisch)", "Manuell (Maus)", " " }));
        platzierungModusCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platzierungModusComboActionPerformed(evt);
            }
        });

        jLabel4.setText("Platzierung:");

        erstelleBaumBtn.setText("Erstellen");
        erstelleBaumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erstelleBaumBtnActionPerformed(evt);
            }
        });

        resetBtn.setText("Zürücksetzen");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Gesamtkosten:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(anzahlKnotenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(graphBuildCbx))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(erstelleBaumBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resetBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(5, 5, 5)
                                .addComponent(platzierungModusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(totalEdgesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(anzahlKnotenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(graphBuildCbx)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(platzierungModusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(erstelleBaumBtn)
                        .addComponent(resetBtn))
                    .addComponent(totalEdgesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Simulation"));

        jLabel1.setText("Verzögerung:");

        runBtn.setText("Los!");
        runBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runBtnActionPerformed(evt);
            }
        });

        delaySlider.setMaximum(1000);
        delaySlider.setMinorTickSpacing(100);
        delaySlider.setPaintTicks(true);
        delaySlider.setSnapToTicks(true);
        delaySlider.setToolTipText("Sekunden");
        delaySlider.setNextFocusableComponent(delaySlider);
        delaySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                delaySliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(delayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(delaySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(runBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(delayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delaySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(runBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(nodePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nodePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void erstelleBaumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erstelleBaumBtnActionPerformed
        if (platzierungModusCombo.getSelectedIndex() == 0) {
            if (anzahlKnotenTxt.getText().isEmpty()) {
                anzahlKnotenTxt.setText("2");
            }
            int nodeCount = Integer.valueOf(anzahlKnotenTxt.getText());
            if (nodeCount <= 0) {
                nodeCount = 2;
                anzahlKnotenTxt.setText(String.valueOf(nodeCount));
            }
            //Zufällige Anordnung
            platziereZufaellig(Integer.valueOf(anzahlKnotenTxt.getText()), nodePanel.getSize());
            drawGraph();
            runBtn.setEnabled(true);
            progressBar.setValue(0);

        } else {
            //Manuell
        }
    }//GEN-LAST:event_erstelleBaumBtnActionPerformed

    private void runBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runBtnActionPerformed
        graph.setDelay(delaySlider.getValue());
        progressBar.setMaximum(graph.getNodeCount() - 1);
        progressBar.setValue(0);
        graph.minimalSpanningTree(this);
        runBtn.setEnabled(false);

    }//GEN-LAST:event_runBtnActionPerformed

    private void platzierungModusComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platzierungModusComboActionPerformed
        reset();
        erstelleBaumBtn.setVisible(platzierungModusCombo.getSelectedIndex() == 0);


    }//GEN-LAST:event_platzierungModusComboActionPerformed

    private void anzahlKnotenTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anzahlKnotenTxtActionPerformed

    }//GEN-LAST:event_anzahlKnotenTxtActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        reset();

        runBtn.setEnabled(false);

    }//GEN-LAST:event_resetBtnActionPerformed

    private void nodePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nodePanelMouseClicked

        if (platzierungModusCombo.getSelectedIndex() == 1) {
            Graphics2D g2d = (Graphics2D) nodePanel.getGraphics();
            int x = evt.getX() - Node.width / 2;
            int y = evt.getY() - Node.width / 2;
            graph.addNode(graph.getNodeCount(), x, y);
            graph.draw(g2d, graphBuildCbx.isSelected());
            anzahlKnotenTxt.setText(String.valueOf(graph.getNodeCount()));
        }

        if (graph != null) {
            runBtn.setEnabled(graph.getNodeCount() > 1);
        }

    }//GEN-LAST:event_nodePanelMouseClicked

    private void delaySliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_delaySliderStateChanged
        delayLbl.setText(delaySlider.getValue() + " ms");

    }//GEN-LAST:event_delaySliderStateChanged

    /**
     *
     */
    private void reset() {

        graph = new Graph(nodePanel.getSize());
        nodePanel.getGraphics().fillRect(0, 0, nodePanel.getWidth(), nodePanel.getHeight());
        totalEdgesLbl.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visuell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visuell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visuell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visuell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visuell().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anzahlKnotenTxt;
    private javax.swing.JLabel delayLbl;
    private javax.swing.JSlider delaySlider;
    private javax.swing.JButton erstelleBaumBtn;
    private javax.swing.JCheckBox graphBuildCbx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel nodePanel;
    private javax.swing.JComboBox<String> platzierungModusCombo;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton runBtn;
    private javax.swing.JLabel totalEdgesLbl;
    // End of variables declaration//GEN-END:variables

    public JProgressBar getProgressBar() {
        return progressBar;
    }

    public JPanel getPanel() {
        return nodePanel;
    }

    public JLabel getTotalEdgesLbl() {
        return totalEdgesLbl;
    }

    /**
     *
     */
    private void platziereZufaellig(int count, Dimension dimension) {

        if (count < 0) {
            return;
        }

        reset();

        graph = new Graph(dimension);
        graph.init(count);
        graph.fillRandomly();

    }

    /**
     *
     */
    private void drawGraph() {

        graph.draw(nodePanel.getGraphics(), graphBuildCbx.isSelected());
    }

    @Override
    public void focusGained(FocusEvent e) {
    }

}
